Partially solve #2200
spring-projects/spring-data-commons pull request #2274
Opened 2021-01-16 00:05 UTC by matiasah

This pull request partially solves #2200 Adds `QuerydslWebFluxConfiguration` and `QuerydslPredicateArgumentResolver` for WebFlux.

It's necessary to solve #1846 to completely close #2200.

2021-01-16 00:05 UTC, pivotal-issuemaster commented
@matiasah Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2274)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2274) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-01-16 00:06 UTC, pivotal-issuemaster commented
@matiasah Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2274)!

2021-01-18 13:37 UTC, mp911de requested changes
Thanks for your contribution. Please make sure to use tab indentation (see our formatting settings at https://github.com/spring-projects/spring-data-build/blob/master/etc/ide/eclipse-formatting.xml) and consider comments from #2200.

2021-01-19 00:11 UTC, matiasah commented
I applied the formatting settings on Visual Studio Code RedHat Java Plugin with the eclipse formatting (the link you commented on raw form), and auto-indented the files I modified. Is it good enough or should I install Eclipse to do that?

2021-01-19 08:00 UTC, mp911de commented
Using a plugin that follows Eclipse formatting is perfectly fine, no need to use Eclipse. From a quick look, the code style looks fine now.

2021-01-19 08:08 UTC, mp911de reviewed
Thanks a lot. The changes look pretty good. I left few comments addressing very minor issues. Care to have a look and squash your commits once done? Feel free to force-push and leave a comment once we should have another look.

2021-01-19 08:08 UTC, mp911de commented on src/main/java/org/springframework/data/web/config/ReactiveQuerydslWebConfiguration.java
> + * @author Oliver Gierke
Nit: That's a new class. No need to copy over the original authors, having just you as `@author` is sufficient.

2021-01-19 08:08 UTC, mp911de commented on src/main/java/org/springframework/data/web/config/ReactiveQuerydslWebConfiguration.java
> +	 * Spring MVC controller methods.
Nit: Spring WebFlux (instead MVC).

2021-01-19 08:08 UTC, mp911de commented on src/main/java/org/springframework/data/web/querydsl/ReactiveQuerydslPredicateArgumentResolver.java
> +		// TODO Auto-generated constructor stub
Nit: There are a few `TODO` comments that should be removed.

2021-01-19 08:08 UTC, mp911de commented on src/main/java/org/springframework/data/web/querydsl/ReactiveQuerydslPredicateArgumentResolver.java
> + * @author Christoph Strobl
Nit: You're the original author, so no need to copy over the original authors.

2021-01-19 22:27 UTC, matiasah commented
I'm not sure if I squashed the commits correctly.

2021-01-25 14:58 UTC, mp911de commented
Thank you for your contribution. That's merged and polished now.

On a related note: Make sure to configure your local Git client with a proper name and mail address as the author of your commits is `Ubuntu <Ubuntu>`. We fixed that in the course of the merge.

2021-01-25 14:58 UTC, closed without merging