Unify return types in PageRequest.
spring-projects/spring-data-commons pull request #2318
Opened 2021-03-02 08:55 UTC by Artur-

- [X] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

2021-03-02 08:55 UTC, pivotal-issuemaster commented
@Artur- Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2318)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2318) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-03-02 08:56 UTC, pivotal-issuemaster commented
@Artur- Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2318)!

2021-03-15 16:15 UTC, mp911de requested changes

2021-03-15 16:15 UTC, mp911de commented on src/main/java/org/springframework/data/domain/PageRequest.java
> +	public Pageable previous() {
We should rather change the other methods to return `PageRequest` as that is the more concrete type and we retain type-safety. Care to have a look?

2021-03-30 09:38 UTC, closed without merging

2021-03-30 09:38 UTC, mp911de commented
Since there was no further activity we decided to handle the changes ourselves.