Introduce Limit.
spring-projects/spring-data-commons pull request #2836
Opened 2023-05-31 11:27 UTC by christophstrobl

`Limit` can be used as `Parameter` within repository query methods to define the maximum number of results to be returned. 

```java
List<Person> findByFirstnameLike(String firstname, Limit limit);

List<Person> findByFirstnameLike(String firstname, Sort orderBy, Limit limit);

Window<User> findByFirstnameLikeOrderByLastname(ScrollPosition pageable, Limit limit);
```

The default `ParameterAccessor` implementation will pick up `Limit` and `Sort` to assemble a `Pageable` out of the provided values if present to provide out of the box support for modules using `ParameterAcessor#getPageable()` to apply order and limit.

`Limit#max` is aligned to `Page.size`, both using `int`. We might want to consider `long` for `Limit` and error if the actual value exceeds the `Page` one when assembling the `Pageable`.

2023-06-01 15:43 UTC, odrotbohm reviewed
A couple of minor findings.

2023-06-01 15:43 UTC, odrotbohm commented on src/main/asciidoc/repositories-paging-sorting.adoc
> +The `Top` keyword used to limit results can be used to along with `Pageable` whereas `Top` defines the total maximum of results, whereas the Pageable parameter may reduce this this number.
Double "this this"?

2023-06-01 15:43 UTC, odrotbohm commented on src/main/java/org/springframework/data/repository/query/QueryMethod.java
> +	public void validate() {
Needs to be public?

2023-06-01 15:43 UTC, odrotbohm reviewed
A couple of minor findings.

2023-07-04 14:01 UTC, mp911de requested changes
Left some comments, seconding what Ollie said.

2023-07-05 09:54 UTC, mp911de commented
That's merged and polished now.

2023-07-05 09:54 UTC, closed without merging