DATACMNS-1699 - Add Embedded annotation.
spring-projects/spring-data-commons pull request #480
Opened 2020-12-15 09:22 UTC by christophstrobl

Add core annotation for embedded object support and consider a potential prefix when using `FieldNamingStrategies`.

The actual store specific implementation is done in the individual modules that make sure the mapping context provides means to detect embedded types and provide this information to the `PersistentPropertyPathFactory` now using` `PersistentEntities` instead of the `TypeInformation` to construct mapped paths.

2020-12-18 18:44 UTC, schauder requested changes

2020-12-18 18:44 UTC, schauder commented on src/main/java/org/springframework/data/mapping/PersistentProperty.java
> +		return (isEmbedded() && findAnnotation(Embedded.class).onEmpty().equals(OnEmpty.USE_NULL))
When a property is not embedded, it is never nullable. If that is intended, it should be described in the documentation and the superfluous parens around the first `&&` term should be removed. 

Or the expression should get fixed. Also we should have tests for the not embedded case.

2021-01-13 03:24 UTC, dcominottim commented
It'd be really nice if we could further customize this annotation with more parameters or pair it with another annotation to achieve the same effect from `@Embedded` +` @AttributeOverride` from `javax.persistence`. This way, the name of the inline fields could be customized and the embeddable objects could be re-used in different parent objects that need different field names for inline fields.

2021-01-13 09:46 UTC, mp911de commented
Embedded objects are conceptually stable regarding their property to field/column/… names. `@Embedded` allows you to provide a prefix to customize physical naming. An example use-case:

```java
class Address {
  String street, city;
}

class Order {

  @Embedded(prefix = "shipping_")
  Address shipping;

  @Embedded(prefix = "billing_")
  Address billing;
}
```

Rendering fields `shipping_street`, `shipping_city`, `billing_street`, and so on.

@dcominottim care to elaborate how else you'd like to customize field names?

2021-01-13 18:26 UTC, dcominottim commented
> Embedded objects are conceptually stable regarding their property to field/column/… names. `@Embedded` allows you to provide a prefix to customize physical naming. An example use-case:
> 
> ```java
> class Address {
>   String street, city;
> }
> 
> class Order {
> 
>   @Embedded(prefix = "shipping_")
>   Address shipping;
> 
>   @Embedded(prefix = "billing_")
>   Address billing;
> }
> ```
> 
> Rendering fields `shipping_street`, `shipping_city`, `billing_street`, and so on.
> 
> @dcominottim care to elaborate how else you'd like to customize field names?

Thanks for the reply, @mp911de. I had overlooked the 'prefix' param. It seems to work fine for embedded objects that aggregate multiple properties (such as your `Address` example). I think it should often work for value objects that encapsulate a single property as well (e.g.: `class CompanyName { String companyName; }`), although it'd still be useful for the parent to be able to fully override that -- in JPA, it'd be

```java
class Company {
  @Embedded
  @AttributeOverride(
    name = "companyName", // name of the target attribute
    column = @Column(name = "CMP_NAME") // name that will be used for persistence
  )
  CompanyName name;
}
```

Think of a scenario in which the company you work for has complex rules for data modeling and the data governance team may request you to use specific column/attribute names for certain tables/documents -- and they don't play well with Java/Spring Data attribute naming conventions. I am in such scenario right now and need to use @AttributeOverride in JPA projects.

On a separate note, does Spring Data fully support underscore in attribute names nowadays (as per your prefix example)? It didn't use to. Sorry if too obvious. https://github.com/spring-projects/spring-data-commons/pull/126

2021-01-20 08:31 UTC, sseep commented
Thank you for open source contribution.  The feature still be watched?

2021-02-08 16:24 UTC, mp911de commented
Superseded by #2294.

2021-02-16 13:46 UTC, closed without merging